"""Build a reviewed SQL microorganism catalog from the captured SIMCORE list."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import unicodedata
from pathlib import Path


SOURCE_SHA256 = "57069e2ccada6ee7cde5dd3d0cacf3c1e6980435f3900c6be3e0f5029e0fbd56"
EXPECTED_SOURCE_LINES = 2540
EXPECTED_CANONICAL_ROWS = 2526
EXPECTED_CATALOG_ROWS = 2452

GENERAL_CATEGORY_LINES = {
    18,
    *range(127, 140),
    557,
    663,
    664,
    780,
    995,
    *range(1059, 1071),
    1137,
    1152,
    1410,
    1439,
    1586,
    1631,
    1701,
    2414,
    2521,
    2522,
}
NEGATIVE_RESULT_LINES = set(range(1593, 1618))
OPERATIONAL_LINES = {674, 1403, 1632, 1633, 1634, 1661, 1866, 2475}
QUARANTINE_BY_LINE = {
    **{line: "GENERAL_CATEGORY" for line in GENERAL_CATEGORY_LINES},
    **{line: "NEGATIVE_RESULT" for line in NEGATIVE_RESULT_LINES},
    **{line: "OPERATIONAL" for line in OPERATIONAL_LINES},
}


def normalize_name(value: str) -> str:
    normalized = unicodedata.normalize("NFC", value.replace("\xa0", " "))
    return " ".join(normalized.split())


def load_catalog(source: Path) -> tuple[list[str], list[tuple[int, str, str]], dict[str, int]]:
    raw = source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(f"Unexpected source SHA-256: {digest}")

    lines = raw.decode("cp1252").splitlines()
    if len(lines) != EXPECTED_SOURCE_LINES:
        raise ValueError(f"Expected {EXPECTED_SOURCE_LINES} source lines, found {len(lines)}")

    canonical: list[tuple[int, str]] = []
    seen: set[str] = set()
    discarded = 0
    duplicates = 0
    for line_number, raw_name in enumerate(lines, start=1):
        name = normalize_name(raw_name)
        if not name or name.startswith(("var ", "copy(", "console.log(")):
            discarded += 1
            continue
        key = name.casefold()
        if key in seen:
            duplicates += 1
            continue
        seen.add(key)
        canonical.append((line_number, name))

    if len(canonical) != EXPECTED_CANONICAL_ROWS:
        raise ValueError(f"Expected {EXPECTED_CANONICAL_ROWS} canonical rows, found {len(canonical)}")

    catalog = [name for line_number, name in canonical if line_number not in QUARANTINE_BY_LINE]
    quarantine = [
        (line_number, name, QUARANTINE_BY_LINE[line_number])
        for line_number, name in canonical
        if line_number in QUARANTINE_BY_LINE
    ]
    if len(quarantine) != len(QUARANTINE_BY_LINE):
        raise ValueError("Not every reviewed quarantine line was found in the canonical source")
    if len(catalog) != EXPECTED_CATALOG_ROWS:
        raise ValueError(f"Expected {EXPECTED_CATALOG_ROWS} catalog rows, found {len(catalog)}")
    if any(len(name) > 180 for name in catalog):
        raise ValueError("At least one scientific name exceeds VARCHAR(180)")

    stats = {
        "source_lines": len(lines),
        "discarded_lines": discarded,
        "duplicates": duplicates,
        "canonical_rows": len(canonical),
        "quarantine_rows": len(quarantine),
        "catalog_rows": len(catalog),
    }
    return catalog, quarantine, stats


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_sql(catalog: list[str], stats: dict[str, int]) -> str:
    values = ",\n".join(f"    ({sql_literal(name)})" for name in catalog)
    return f"""-- Generated by backend/scripts/build_organism_catalog.py.
-- Source rows: {stats['source_lines']}; duplicates removed: {stats['duplicates']}.
-- Non-scientific values quarantined: {stats['quarantine_rows']}.
-- Catalog rows: {stats['catalog_rows']}.
-- This standalone table is an exchange artifact. MUFFIN uses organism as its
-- operational catalog; import reviewed rows there instead of deploying both.

SET client_encoding = 'UTF8';
BEGIN;

CREATE TABLE IF NOT EXISTS catalogo_microorganismos (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_cientifico VARCHAR(180) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_catalogo_microorganismos_nombre_norm
ON catalogo_microorganismos (
    lower(regexp_replace(btrim(nombre_cientifico), '[[:space:]]+', ' ', 'g'))
);

INSERT INTO catalogo_microorganismos (nombre_cientifico)
VALUES
{values}
ON CONFLICT DO NOTHING;

COMMIT;
"""


def write_quarantine(path: Path, rows: list[tuple[int, str, str]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as output:
        writer = csv.writer(output)
        writer.writerow(("linea_origen", "valor", "motivo"))
        writer.writerows(rows)


def main() -> None:
    project_root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=project_root / "lista.txt")
    parser.add_argument("--sql-output", type=Path, default=project_root / "docs" / "catalogo_microorganismos.sql")
    parser.add_argument(
        "--quarantine-output",
        type=Path,
        default=project_root / "docs" / "catalogo_microorganismos_cuarentena.csv",
    )
    parser.add_argument(
        "--migration-data-output",
        type=Path,
        default=project_root / "backend" / "alembic" / "data" / "organisms_v1.json",
    )
    args = parser.parse_args()

    catalog, quarantine, stats = load_catalog(args.source)
    args.sql_output.write_text(render_sql(catalog, stats), encoding="utf-8")
    write_quarantine(args.quarantine_output, quarantine)
    args.migration_data_output.write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(
        "Catalog generated: "
        f"{stats['catalog_rows']} rows, {stats['duplicates']} duplicates removed, "
        f"{stats['quarantine_rows']} rows quarantined."
    )


if __name__ == "__main__":
    main()
